algoritmo "Creusa01-2.0"
var
   N1, N2, N3 : real
inicio
       Escreva (" Em que ano nos estamos? ")
       Leia (N1)
       escreva (" Em que ano eu nasci? ")
       Leia (N2)
       N3<- (N1-N2)
       escreva (" Em ",N1, " Voce tera"  , N3, " anos ")
       se ( n3  >= 21) entao
          escreva ("e voce ja tera atingido a maioridade")
       senao
          escreva ("e voce ainda nao atingiu a maioridade")
       fimse
       
fimalgoritmo